### ISSUE TITLE
[QUESTION] Why didn't you benchmark Mo?

### ISSUE THREAD

**Issue by XSven** [kfly8/bench-perl-class-builder#8]
`Mo` follows a clean and public philosophy [Mo::Design](https://metacpan.org/dist/Mo/view/lib/Mo/Design.pod). Any reason why this class builder wasn't benchmarked too?

**Comment by kfly8** [comment]
Thanks for the comment.
No particular reason.
If Mo wants to compare too, I would be happy to get a pull request!
